name: Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install \
            pytest \
            asv==0.6.6 \
            numpy==2.5.3 \
            onnx==1.23.1 \
            onnxruntime==1.30.0 \
            torch \
            transformers==5.15.0 \
            "scipy>=1.18.0" \
            "ml_dtypes>=0.6.0" \
            https://github.com/xadupre/onnx-light/releases/download/0.1.28/onnx_light-0.1.28-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
          python -m pip install --no-deps \
            "modelbuilder @ git+https://github.com/xadupre/mbext.git@aadae02d50480298db28716e4769a13b3d82f819"
      - name: Run unit tests
        run: python -m pytest tests
